### ISSUE TITLE
NullPointerException: Parameter specified as non-null is null:

### ISSUE THREAD

**Issue by ben-manes** [JetBrains/lincheck#266]
```console
Gradle suite > Gradle test > com.github.benmanes.caffeine.lincheck.CaffeineLincheckTest$BoundedLincheckTest > modelCheckingTest FAILED
    java.lang.ExceptionInInitializerError
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:270)
        at com.github.benmanes.caffeine.cache.SS.<init>(Unknown Source)
        at com.github.benmanes.caffeine.cache.SSMS.<init>(Unknown Source)
        at com.github.benmanes.caffeine.cache.SSMSW.<init>(Unknown Source)
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:48)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3953)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:4451)
        at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1073)
        at com.github.benmanes.caffeine.lincheck.AbstractLincheckCacheTest.<init>(AbstractLincheckCacheTest.java:47)
        at com.github.benmanes.caffeine.lincheck.CaffeineLincheckTest$BoundedLincheckTest.<init>(CaffeineLincheckTest.java:40)

        Caused by:
        java.lang.NullPointerException: Parameter specified as non-null is null: method org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.identityHashCodeDeterministic$lincheck, parameter obj
            at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.identityHashCodeDeterministic$lincheck(ManagedStrategy.kt)
            at com.github.benmanes.caffeine.cache.References$WeakKeyReference.<init>(References.java:188)
            at com.github.benmanes.caffeine.cache.NodeFactory$RetiredWeakKey.<init>(NodeFactory.java:160)
            at com.github.benmanes.caffeine.cache.NodeFactory.<clinit>(NodeFactory.java:38)
            ... 10 more
```

This is when the [build](https://github.com/ben-manes/caffeine/actions/runs/7722668091/job/21052354908?pr=1493) upgrades from 2.18.1 to 2.24. The hash of `null` is well defined (zero by System.identityHashCode` so I think this method should be loosened. The instrumented constructors all handle this null parameters properly.

**Comment by ben-manes** [comment]
When trying to work around this a different NPE appears,

```console
java.lang.NullPointerException: it.first must not be null
	at org.jetbrains.kotlinx.lincheck.runner.ParallelThreadsRunner.run(ParallelThreadsRunner.kt:286)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.runInvocation(ManagedStrategy.kt:243)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.modelchecking.ModelCheckingStrategy.runImpl(ModelCheckingStrategy.kt:62)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.run(ManagedStrategy.kt:130)
	at org.jetbrains.kotlinx.lincheck.LinChecker.run(LinChecker.kt:126)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl(LinChecker.kt:80)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl$lincheck(LinChecker.kt:52)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt:42)
```
