### ISSUE TITLE
IAE: Internal error after adding a @StateRepresentation function to the concurrent-linked-deque-bug example

### ISSUE THREAD

**Issue by OliverO2** [JetBrains/lincheck#345]
Using [concurrent-linked-deque-bug](https://github.com/ndkoval/concurrent-linked-deque-bug) at its initial commit 0f685f8, and adding the following function to the test class

```kotlin
    @StateRepresentation
    fun stateRepresentation() = "$deque"
```

produces the following output:
```
Non-determinism found. Probably caused by non-deterministic code (WeakHashMap, Object.hashCode, etc).
== Reporting the first execution without execution trace ==
= Invalid execution results =
| ------------------------------------------------- |
|        Thread 1         |        Thread 2         |
| ------------------------------------------------- |
| peekLast(): null        |                         |
| addLast(0): void        |                         |
| peekFirst(): 1          |                         |
| addFirst(1): void       |                         |
| pollFirst(): 1          |                         |
| ------------------------------------------------- |
| STATE: [1]                                        |
| ------------------------------------------------- |
| pollFirst(): 1          | addLast(-1): void       |
| pollLast(): 0 [1,5]     | pollLast(): 1 [0,1]     |
| addLast(1): void [2,5]  | peekFirst(): 1 [0,2]    |
| pollFirst(): 1 [3,5]    | addFirst(0): void [0,3] |
| addFirst(2): void [4,5] | peekLast(): 1 [0,4]     |
| ------------------------------------------------- |
| STATE: [2]                                        |
| ------------------------------------------------- |
| addFirst(-2): void      |                         |
| addFirst(-1): void      |                         |
| pollFirst(): -1         |                         |
| pollFirst(): -2         |                         |
| pollLast(): 2           |                         |
| ------------------------------------------------- |
| STATE: []                                         |
| ------------------------------------------------- |

---
All operations above the horizontal line | ----- | happen before those below the line
---
Values in "[..]" brackets indicate the number of completed operations
in each of the parallel threads seen at the beginning of the current operation
---

== Reporting the second execution ==
Wow! You've caught a bug in Lincheck.
We kindly ask to provide an issue here: https://github.com/JetBrains/lincheck/issues,
attaching a stack trace printed below and the code that causes the error.

Exception stacktrace:
java.lang.IllegalArgumentException: Internal error
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ReplayModeLoopDetectorHelper.shouldSwitch(LoopDetector.kt:451)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.LoopDetector.shouldSwitchInReplayMode(LoopDetector.kt:120)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.newSwitchPoint(ManagedStrategy.kt:363)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.beforeReadField(ManagedStrategy.kt:720)
	at sun.nio.ch.lincheck.Injections.beforeReadField(Injections.java:181)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.updateTail(ConcurrentLinkedDeque.java:599)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.unlinkLast(ConcurrentLinkedDeque.java:540)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.unlink(ConcurrentLinkedDeque.java:391)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.pollLast(ConcurrentLinkedDeque.java:942)
	at ConcurrentLinkedDequeTest.pollLast(ConcurrentLinkedDequeTest.kt:23)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution90.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:174)
	at java.base/java.lang.Thread.run(Thread.java:840)


java.lang.IllegalStateException: Non-determinism found. Probably caused by non-deterministic code (WeakHashMap, Object.hashCode, etc).
== Reporting the first execution without execution trace ==
= Invalid execution results =
| ------------------------------------------------- |
|        Thread 1         |        Thread 2         |
| ------------------------------------------------- |
| peekLast(): null        |                         |
| addLast(0): void        |                         |
| peekFirst(): 1          |                         |
| addFirst(1): void       |                         |
| pollFirst(): 1          |                         |
| ------------------------------------------------- |
| STATE: [1]                                        |
| ------------------------------------------------- |
| pollFirst(): 1          | addLast(-1): void       |
| pollLast(): 0 [1,5]     | pollLast(): 1 [0,1]     |
| addLast(1): void [2,5]  | peekFirst(): 1 [0,2]    |
| pollFirst(): 1 [3,5]    | addFirst(0): void [0,3] |
| addFirst(2): void [4,5] | peekLast(): 1 [0,4]     |
| ------------------------------------------------- |
| STATE: [2]                                        |
| ------------------------------------------------- |
| addFirst(-2): void      |                         |
| addFirst(-1): void      |                         |
| pollFirst(): -1         |                         |
| pollFirst(): -2         |                         |
| pollLast(): 2           |                         |
| ------------------------------------------------- |
| STATE: []                                         |
| ------------------------------------------------- |

---
All operations above the horizontal line | ----- | happen before those below the line
---
Values in "[..]" brackets indicate the number of completed operations
in each of the parallel threads seen at the beginning of the current operation
---

== Reporting the second execution ==
Wow! You've caught a bug in Lincheck.
We kindly ask to provide an issue here: https://github.com/JetBrains/lincheck/issues,
attaching a stack trace printed below and the code that causes the error.

Exception stacktrace:
java.lang.IllegalArgumentException: Internal error
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ReplayModeLoopDetectorHelper.shouldSwitch(LoopDetector.kt:451)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.LoopDetector.shouldSwitchInReplayMode(LoopDetector.kt:120)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.newSwitchPoint(ManagedStrategy.kt:363)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.beforeReadField(ManagedStrategy.kt:720)
	at sun.nio.ch.lincheck.Injections.beforeReadField(Injections.java:181)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.updateTail(ConcurrentLinkedDeque.java:599)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.unlinkLast(ConcurrentLinkedDeque.java:540)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.unlink(ConcurrentLinkedDeque.java:391)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.pollLast(ConcurrentLinkedDeque.java:942)
	at ConcurrentLinkedDequeTest.pollLast(ConcurrentLinkedDequeTest.kt:23)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution90.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:174)
	at java.base/java.lang.Thread.run(Thread.java:840)


	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.collectTrace(ManagedStrategy.kt:255)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.checkResult(ManagedStrategy.kt:210)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.modelchecking.ModelCheckingStrategy.runImpl(ModelCheckingStrategy.kt:73)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.run(ManagedStrategy.kt:147)
	at org.jetbrains.kotlinx.lincheck.LinChecker.run(LinChecker.kt:153)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl(LinChecker.kt:91)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl$lincheck(LinChecker.kt:58)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt:45)
	at org.jetbrains.kotlinx.lincheck.LinChecker$Companion.check(LinChecker.kt:180)
	at org.jetbrains.kotlinx.lincheck.LinCheckerKt.check(LinChecker.kt:195)
	at org.jetbrains.kotlinx.lincheck.LinCheckerKt.check(LinChecker.kt:204)
	at ConcurrentLinkedDequeTest.modelCheckingTest(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)


OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
> Task :test
ConcurrentLinkedDequeTest > modelCheckingTest FAILED
    java.lang.IllegalStateException at null:35
1 test completed, 1 failed
```

**Comment by ndkoval** [comment]
Lincheck 2.33 also fails with non-determinism and the following exceptions:

```
#3: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ReplayModeLoopDetectorHelper.getCurrentHistoryNode(LoopDetector.kt:645)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ReplayModeLoopDetectorHelper.getCurrentlyInSpinCycle(LoopDetector.kt:651)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.LoopDetector.getReplayModeCurrentlyInSpinCycle(LoopDetector.kt:120)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy$TraceCollector.checkActiveLockDetected(ManagedStrategy.kt:1392)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.beforeMethodCall(ManagedStrategy.kt:899)
	at sun.nio.ch.lincheck.Injections.beforeMethodCall(Injections.java:249)
	at ConcurrentLinkedDequeTest.peekLast(ConcurrentLinkedDequeTest.kt:28)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution90.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:174)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Notable, `CLD.toString()` modifies the data structure state, which might have caused the issue. Need further investigation.

**Comment by OliverO2** [comment]
> Notable, CLD.toString() modifies the data structure state, which might have caused the issue.

That's something that I was suspecting, too. If I'm not missing something, we'd rely on `@StateRepresentation` functions observing two invariants:
1. They must not change the structure under test.
2. They must not introduce additional access patterns which interfere with Lincheck.

Since we need such functions particularly _if_ a concurrent data structure produces errors, this may become impossible, right? If so, wouldn't it be preferable to track state in a separate data structure, which does not affect Lincheck? Maybe the docs should mention how to construct one that's safe to use with Lincheck.

**Comment by ndkoval** [comment]
We are about to deprecate this functionality and provide an IntelliJ IDEA plugin that enables data structure visualization at each step.

**Comment by ndkoval** [comment]
You can already try it: https://plugins.jetbrains.com/plugin/24171-lincheck

**Comment by ndkoval** [comment]
I am closing this issue as "not planned". @OliverO2, thanks for catching the bug and creating the issue!
