### ISSUE TITLE
Filter stack traces of exceptions thrown inside validation function

### ISSUE THREAD

**Issue by eupp** [JetBrains/lincheck#438]
Currently that validation function stack traces are handled differently compared to other stack traces printed by Lincheck.

In particular, the stack trace elements corresponding to Lincheck internals are not filtered (see, [validation_function_failure.txt](https://github.com/JetBrains/lincheck/blob/master/src/jvm/test/resources/expected_logs/validation_function_failure.txt), last 3 stack frames):

```
	java.lang.IllegalStateException: Validation works!
	at org.jetbrains.kotlinx.lincheck_test.representation.ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:44)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution196.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:172)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

We need to fix this problem to handle these exceptions similarly as other exceptions, and filter the stack traces.

**Comment by eupp** [comment]
Migrated to YT
